### PR TITLE
Add config for failed builds channel

### PR DESCRIPTION
**Pull request by thatportugueseguy**
This PR adds a config for a failed builds channel. This is a channel where notifications for failed builds get posted with the new CI steps that were broken, with an @mention for the slack user who committed the changes that broke the CI.

Only newly broken CI steps get notified, so when a user's commit breaks a step that was already notified, it doesn't get notified again.

### CODE REVIEW

**Comment by Khady** [comment]
do you have a screenshot to show the final result?

**Comment by thatportugueseguy** [comment]
Screenshot 2024-10-14 at 09 17 37

Actually, looking again at the screenshot, I'm left thinking that we can make the notification more minimal and in line with the changes in https://github.com/ahrefs/monorobot/pull/162.. We don't need to have a duplicate commit message, and we don't need the author in the commit lie, since we are identifying them in the slack mention.

**Comment by Khady** [comment]
are `steps broken` the new failures or all the steps that failed in a given build?

**Comment by thatportugueseguy** [comment]
only new failures. No preexisting failures are notified. On build `#159` in the screenshot above, there are three failing steps, but only the two new ones are notified, with the author of the current commit in mention.

**Comment by thatportugueseguy** [comment]
I've made the notification a bit more minimal, I think it looks good. I'm happy to merge now 

Screenshot 2024-10-15 at 09 22 24

**Comment by Khady** [comment]
should we also notify when the build gets fixed?

**Comment by Khady** [comment]
can you update the documentation please

**Comment by Khady** [comment]
I guess we should have made the notification of committer optional too

**Comment by Khady** [comment]
those notifications will ony be for the main branch right?

**Comment by Khady** [comment]
> those notifications will ony be for the main branch right?

They are not. I think it's a problem

**Pull request merged**
